# SPDX-FileCopyrightText: © 2022 Wojciech Trybus <wojtryb@gmail.com>
# SPDX-License-Identifier: GPL-3.0-or-later

from krita import Krita as Api
from enum import Enum

from PyQt5.QtGui import QIcon


class Action(Enum):
    """
    Contains all known actions of Krita.

    Example usage: `Tool.FREEHAND_BRUSH`

    Available actions:
    - `TBA`
    """

    # Filters
    FILTER_APPLY_AGAIN = "filter_apply_again" # Apply Filter Again
    FILTER_APPLY_REPROMPT = "filter_apply_reprompt" # Apply Filter Again (Reprompt)
    ADJUST_FILTERS = "adjust_filters" # Adjust
    KRITA_FILTER_ASC_CDL = "krita_filter_asc-cdl" # Slope, Offset, Power...
    KRITA_FILTER_AUTOCONTRAST = "krita_filter_autocontrast" # Auto Contrast
    BLUR_FILTERS = "blur_filters" # Blur
    KRITA_FILTER_BLUR = "krita_filter_blur" # Blur...
    KRITA_FILTER_BURN = "krita_filter_burn" # Burn...
    KRITA_FILTER_COLORBALANCE = "krita_filter_colorbalance" # Colour Balance...
    COLOR_FILTERS = "color_filters" # Colours
    KRITA_FILTER_COLORTOALPHA = "krita_filter_colortoalpha" # Colour to Alpha...
    KRITA_FILTER_COLORTRANSFER = "krita_filter_colortransfer" # Colour Transfer...
    KRITA_FILTER_CROSSCHANNEL = "krita_filter_crosschannel" # Cross-channel adjustment curves...
    KRITA_FILTER_DESATURATE = "krita_filter_desaturate" # Desaturate...
    KRITA_FILTER_DODGE = "krita_filter_dodge" # Dodge...
    EDGE_FILTERS = "edge_filters" # Edge Detection
    KRITA_FILTER_EDGE_DETECTION = "krita_filter_edge detection" # Edge Detection...
    EMBOSS_FILTERS = "emboss_filters" # Emboss
    KRITA_FILTER_EMBOSS = "krita_filter_emboss" # Emboss with Variable Depth...
    KRITA_FILTER_EMBOSS_ALL_DIRECTIONS = "krita_filter_emboss all directions" # Emboss in All Directions
    KRITA_FILTER_EMBOSS_HORIZONTAL_AND_VERTICAL = "krita_filter_emboss horizontal and vertical" # Emboss Horizontal  Vertical
    KRITA_FILTER_EMBOSS_HORIZONTAL_ONLY = "krita_filter_emboss horizontal only" # Emboss Horizontal Only
    KRITA_FILTER_EMBOSS_LAPLASCIAN = "krita_filter_emboss laplascian" # Emboss (Laplacian)
    KRITA_FILTER_EMBOSS_VERTICAL_ONLY = "krita_filter_emboss vertical only" # Emboss Vertical Only
    KRITA_FILTER_GAUSSIAN_BLUR = "krita_filter_gaussian blur" # Gaussian Blur...
    KRITA_FILTER_GAUSSIANHIGHPASS = "krita_filter_gaussianhighpass" # Gaussian High Pass...
    ENHANCE_FILTERS = "enhance_filters" # Enhance
    KRITA_FILTER_GAUSSIANNOISEREDUCER = "krita_filter_gaussiannoisereducer" # Gaussian Noise Reduction...
    MAP_FILTERS = "map_filters" # Map
    KRITA_FILTER_GRADIENTMAP = "krita_filter_gradientmap" # Gradient Map...
    ARTISTIC_FILTERS = "artistic_filters" # Artistic
    KRITA_FILTER_HALFTONE = "krita_filter_halftone" # Halftone...
    KRITA_FILTER_HEIGHT_TO_NORMAL = "krita_filter_height to normal" # Height to Normal Map...
    KRITA_FILTER_HSVADJUSTMENT = "krita_filter_hsvadjustment" # HSV Adjustment...
    KRITA_FILTER_INDEXCOLORS = "krita_filter_indexcolors" # Index Colours...
    KRITA_FILTER_INVERT = "krita_filter_invert" # Invert
    KRITA_FILTER_LENS_BLUR = "krita_filter_lens blur" # Lens Blur...
    KRITA_FILTER_LEVELS = "krita_filter_levels" # Levels...
    KRITA_FILTER_MAXIMIZE = "krita_filter_maximize" # Maximise Channel
    KRITA_FILTER_MEAN_REMOVAL = "krita_filter_mean removal" # Mean Removal
    KRITA_FILTER_MINIMIZE = "krita_filter_minimize" # Minimise Channel
    KRITA_FILTER_MOTION_BLUR = "krita_filter_motion blur" # Motion Blur...
    OTHER_FILTERS = "other_filters" # Other
    KRITA_FILTER_NOISE = "krita_filter_noise" # Random Noise...
    KRITA_FILTER_NORMALIZE = "krita_filter_normalize" # Normalise
    KRITA_FILTER_OILPAINT = "krita_filter_oilpaint" # Oilpaint...
    KRITA_FILTER_PALETTIZE = "krita_filter_palettize" # Palettise...
    KRITA_FILTER_PERCHANNEL = "krita_filter_perchannel" # Colour Adjustment curves...
    KRITA_FILTER_PHONGBUMPMAP = "krita_filter_phongbumpmap" # Phong Bumpmap...
    KRITA_FILTER_PIXELIZE = "krita_filter_pixelize" # Pixelise...
    KRITA_FILTER_POSTERIZE = "krita_filter_posterize" # Posterise...
    KRITA_FILTER_RAINDROPS = "krita_filter_raindrops" # Raindrops...
    KRITA_FILTER_RANDOMPICK = "krita_filter_randompick" # Random Pick...
    KRITA_FILTER_ROUNDCORNERS = "krita_filter_roundcorners" # Round Corners...
    KRITA_FILTER_SHARPEN = "krita_filter_sharpen" # Sharpen
    KRITA_FILTER_SMALLTILES = "krita_filter_smalltiles" # Small Tiles...
    KRITA_FILTER_THRESHOLD = "krita_filter_threshold" # Threshold...
    KRITA_FILTER_UNSHARP = "krita_filter_unsharp" # Unsharp Mask...
    KRITA_FILTER_WAVE = "krita_filter_wave" # Wave...
    KRITA_FILTER_WAVELETNOISEREDUCER = "krita_filter_waveletnoisereducer" # Wavelet Noise Reducer...
    Q_MIC = "QMic" # Start G'MIC-Qt
    Q_MIC_AGAIN = "QMicAgain" # Re-apply the last G'MIC filter

    # Untagged
    SAVE_INCREMENTAL_VERSION = "save_incremental_version" # Save Incremental Version
    SAVE_INCREMENTAL_BACKUP = "save_incremental_backup" # Save Incremental Backup
    TABLET_DEBUGGER = "tablet_debugger" # Toggle Tablet Debugger
    CREATE_TEMPLATE = "create_template" # Create Template From Image...
    CREATE_COPY = "create_copy" # Create Copy From Current Image
    OPEN_RESOURCES_DIRECTORY = "open_resources_directory" # Open Resources Folder
    ROTATE_CANVAS_RIGHT = "rotate_canvas_right" # Rotate Canvas Right
    ROTATE_CANVAS_LEFT = "rotate_canvas_left" # Rotate Canvas Left
    RESET_CANVAS_ROTATION = "reset_canvas_rotation" # Reset Canvas Rotation
    WRAP_AROUND_MODE = "wrap_around_mode" # Wrap Around Mode
    LEVEL_OF_DETAIL_MODE = "level_of_detail_mode" # Instant Preview Mode
    SOFT_PROOF = "softProof" # Soft Proofing
    GAMUT_CHECK = "gamutCheck" # Out of Gamut Warnings
    SHOW_STATUS_BAR = "showStatusBar" # Show Status Bar
    VIEW_SHOW_CANVAS_ONLY = "view_show_canvas_only" # Show Canvas Only
    RULER_PIXEL_MULTIPLE2 = "ruler_pixel_multiple2" # Use multiple of 2 for pixel scale
    VIEW_RULER = "view_ruler" # Show Rulers
    RULERS_TRACK_MOUSE = "rulers_track_mouse" # Rulers Track Pointer
    ZOOM_TO_100PCT = "zoom_to_100pct" # Reset zoom
    VIEW_ZOOM_IN = "view_zoom_in" # Zoom In
    VIEW_ZOOM_OUT = "view_zoom_out" # Zoom Out
    TOGGLE_ZOOM_TO_FIT = "toggle_zoom_to_fit" # Toggle Zoom Fit to Page
    SETTINGS_ACTIVE_AUTHOR = "settings_active_author" # Active Author Profile
    VIEW_PIXEL_GRID = "view_pixel_grid" # Show Pixel Grid
    TOGGLE_FG_BG = "toggle_fg_bg" # Swap Foreground and Background Colours
    RESET_FG_BG = "reset_fg_bg" # Set Foreground and Background Colours to Black and White
    TOGGLE_BRUSH_OUTLINE = "toggle_brush_outline" # Toggle Brush Outline
    EDIT_CUT = "edit_cut" # Cut
    EDIT_COPY = "edit_copy" # Copy
    EDIT_PASTE = "edit_paste" # Paste
    COPY_SHARP = "copy_sharp" # Copy (sharp)
    CUT_SHARP = "cut_sharp" # Cut (sharp)
    PASTE_NEW = "paste_new" # Paste into New Image
    PASTE_AT = "paste_at" # Paste at Cursor
    PASTE_INTO = "paste_into" # Paste into Active Layer
    PASTE_AS_REFERENCE = "paste_as_reference" # Paste as Reference Image
    PASTE_SHAPE_STYLE = "paste_shape_style" # Paste Shape Style
    COPY_MERGED = "copy_merged" # Copy merged
    SELECT_ALL = "select_all" # Select All
    DESELECT = "deselect" # Deselect
    CLEAR = "clear" # Clear
    RESELECT = "reselect" # Reselect
    INVERT_SELECTION = "invert_selection" # Invert Selection
    COPY_SELECTION_TO_NEW_LAYER = "copy_selection_to_new_layer" # Copy Selection to New Layer
    CUT_SELECTION_TO_NEW_LAYER = "cut_selection_to_new_layer" # Cut Selection to New Layer
    FILL_SELECTION_FOREGROUND_COLOR = "fill_selection_foreground_color" # Fill with Foreground Colour
    FILL_SELECTION_BACKGROUND_COLOR = "fill_selection_background_color" # Fill with Background Colour
    FILL_SELECTION_PATTERN = "fill_selection_pattern" # Fill with Pattern
    FILL_SELECTION_FOREGROUND_COLOR_OPACITY = "fill_selection_foreground_color_opacity" # Fill with Foreground Colour (Opacity)
    FILL_SELECTION_BACKGROUND_COLOR_OPACITY = "fill_selection_background_color_opacity" # Fill with Background Colour (Opacity)
    FILL_SELECTION_PATTERN_OPACITY = "fill_selection_pattern_opacity" # Fill with Pattern (Opacity)
    STROKE_SHAPES = "stroke_shapes" # Stroke selected shapes
    TOGGLE_DISPLAY_SELECTION = "toggle_display_selection" # Display Selection
    RESIZEIMAGETOSELECTION = "resizeimagetoselection" # Trim to Selection
    EDIT_SELECTION = "edit_selection" # Edit Selection
    CONVERT_TO_VECTOR_SELECTION = "convert_to_vector_selection" # Convert to Vector Selection
    CONVERT_TO_RASTER_SELECTION = "convert_to_raster_selection" # Convert to Raster Selection
    CONVERT_SHAPES_TO_VECTOR_SELECTION = "convert_shapes_to_vector_selection" # Convert Shapes to Vector Selection
    CONVERT_SELECTION_TO_SHAPE = "convert_selection_to_shape" # Convert to Shape
    TOGGLE_SELECTION_OVERLAY_MODE = "toggle-selection-overlay-mode" # Toggle Selection Display Mode
    STROKE_SELECTION = "stroke_selection" # Stroke Selection...
    VIEW_SHOW_GUIDES = "view_show_guides" # Show Guides
    VIEW_LOCK_GUIDES = "view_lock_guides" # Lock Guides
    VIEW_SNAP_TO_GUIDES = "view_snap_to_guides" # Snap to Guides
    SHOW_SNAP_OPTIONS_POPUP = "show_snap_options_popup" # Show Snap Options Popup
    VIEW_SNAP_ORTHOGONAL = "view_snap_orthogonal" # Snap Orthogonal
    VIEW_SNAP_NODE = "view_snap_node" # Snap Node
    VIEW_SNAP_EXTENSION = "view_snap_extension" # Snap Extension
    VIEW_SNAP_INTERSECTION = "view_snap_intersection" # Snap Intersection
    VIEW_SNAP_BOUNDING_BOX = "view_snap_bounding_box" # Snap Bounding Box
    VIEW_SNAP_IMAGE_BOUNDS = "view_snap_image_bounds" # Snap Image Bounds
    VIEW_SNAP_IMAGE_CENTER = "view_snap_image_center" # Snap Image Centre
    VIEW_SNAP_TO_PIXEL = "view_snap_to_pixel" # Snap Pixel
    FLATTEN_IMAGE = "flatten_image" # Flatten image
    MERGE_LAYER = "merge_layer" # Merge with Layer Below
    FLATTEN_LAYER = "flatten_layer" # Flatten Layer
    SAVE_GROUPS_AS_IMAGES = "save_groups_as_images" # Save Group Layers...
    CONVERT_GROUP_TO_ANIMATED = "convert_group_to_animated" # Convert group to animated layer
    RESIZEIMAGETOLAYER = "resizeimagetolayer" # Trim to Current Layer
    TRIM_TO_IMAGE = "trim_to_image" # Trim to Image Size
    LAYER_STYLE = "layer_style" # Layer Style...
    COPY_LAYER_STYLE = "copy_layer_style" # Copy Layer Style
    PASTE_LAYER_STYLE = "paste_layer_style" # Paste Layer Style
    MIRROR_NODE_X = "mirrorNodeX" # Mirror Layer Horizontally
    MIRROR_NODE_Y = "mirrorNodeY" # Mirror Layer Vertically
    MIRROR_ALL_NODES_X = "mirrorAllNodesX" # Mirror All Layers Horizontally
    MIRROR_ALL_NODES_Y = "mirrorAllNodesY" # Mirror All Layers Vertically
    ACTIVATE_NEXT_LAYER = "activateNextLayer" # Activate next layer
    ACTIVATE_NEXT_SIBLING_LAYER = "activateNextSiblingLayer" # Activate next sibling layer, skipping over groups.
    ACTIVATE_PREVIOUS_LAYER = "activatePreviousLayer" # Activate previous layer
    ACTIVATE_PREVIOUS_SIBLING_LAYER = "activatePreviousSiblingLayer" # Activate previous sibling layer, skipping over groups.
    SWITCH_TO_PREVIOUSLY_ACTIVE_NODE = "switchToPreviouslyActiveNode" # Activate previously selected layer
    SAVE_NODE_AS_IMAGE = "save_node_as_image" # Save Layer/Mask...
    SAVE_VECTOR_NODE_TO_SVG = "save_vector_node_to_svg" # Save Vector Layer as SVG...
    DUPLICATELAYER = "duplicatelayer" # Duplicate Layer or Mask
    COPY_LAYER_CLIPBOARD = "copy_layer_clipboard" # Copy Layer
    CUT_LAYER_CLIPBOARD = "cut_layer_clipboard" # Cut Layer
    PASTE_LAYER_FROM_CLIPBOARD = "paste_layer_from_clipboard" # Paste Layer
    CREATE_QUICK_GROUP = "create_quick_group" # Quick Group
    CREATE_QUICK_CLIPPING_GROUP = "create_quick_clipping_group" # Quick Clipping Group
    QUICK_UNGROUP = "quick_ungroup" # Quick Ungroup
    SELECT_ALL_LAYERS = "select_all_layers" # All Layers
    SELECT_VISIBLE_LAYERS = "select_visible_layers" # Visible Layers
    SELECT_LOCKED_LAYERS = "select_locked_layers" # Locked Layers
    SELECT_INVISIBLE_LAYERS = "select_invisible_layers" # Invisible Layers
    SELECT_UNLOCKED_LAYERS = "select_unlocked_layers" # Unlocked Layers
    NEW_FROM_VISIBLE = "new_from_visible" # New Layer From Visible
    PIN_TO_TIMELINE = "pin_to_timeline" # Pin to Timeline
    ADD_NEW_PAINT_LAYER = "add_new_paint_layer" # Add Paint Layer
    ADD_NEW_GROUP_LAYER = "add_new_group_layer" # Add Group Layer
    ADD_NEW_CLONE_LAYER = "add_new_clone_layer" # Add Clone Layer
    ADD_NEW_SHAPE_LAYER = "add_new_shape_layer" # Add Vector Layer
    ADD_NEW_ADJUSTMENT_LAYER = "add_new_adjustment_layer" # Add Filter Layer...
    ADD_NEW_FILL_LAYER = "add_new_fill_layer" # Add Fill Layer...
    ADD_NEW_FILE_LAYER = "add_new_file_layer" # Add File Layer...
    ADD_NEW_TRANSPARENCY_MASK = "add_new_transparency_mask" # Add Transparency Mask
    ADD_NEW_FILTER_MASK = "add_new_filter_mask" # Add Filter Mask...
    ADD_NEW_COLORIZE_MASK = "add_new_colorize_mask" # Add Colourise Mask
    ADD_NEW_TRANSFORM_MASK = "add_new_transform_mask" # Add Transform Mask
    ADD_NEW_SELECTION_MASK = "add_new_selection_mask" # Add Local Selection
    CONVERT_TO_PAINT_LAYER = "convert_to_paint_layer" # Convert to Paint Layer
    CONVERT_TO_SELECTION_MASK = "convert_to_selection_mask" # Convert to Selection Mask
    CONVERT_TO_FILTER_MASK = "convert_to_filter_mask" # Convert to Filter Mask...
    CONVERT_TO_TRANSPARENCY_MASK = "convert_to_transparency_mask" # Convert to Transparency Mask
    CONVERT_TO_ANIMATED = "convert_to_animated" # Convert to animated layer
    CONVERT_TO_FILE_LAYER = "convert_to_file_layer" # to File Layer...
    ISOLATE_ACTIVE_LAYER = "isolate_active_layer" # Isolate Active Layer
    ISOLATE_ACTIVE_GROUP = "isolate_active_group" # Isolate Active Group
    TOGGLE_LAYER_VISIBILITY = "toggle_layer_visibility" # Toggle layer visibility
    TOGGLE_LAYER_LOCK = "toggle_layer_lock" # Toggle layer lock
    TOGGLE_LAYER_INHERIT_ALPHA = "toggle_layer_inherit_alpha" # Toggle layer alpha inheritance
    TOGGLE_LAYER_ALPHA_LOCK = "toggle_layer_alpha_lock" # Toggle layer alpha
    SPLIT_ALPHA_INTO_MASK = "split_alpha_into_mask" # Alpha into Mask
    SPLIT_ALPHA_WRITE = "split_alpha_write" # Write as Alpha
    SPLIT_ALPHA_SAVE_MERGED = "split_alpha_save_merged" # Save Merged...
    IMPORT_LAYER_FROM_FILE = "import_layer_from_file" # Import Layer...
    IMAGE_PROPERTIES = "image_properties" # Properties...
    IMPORT_LAYER_AS_PAINT_LAYER = "import_layer_as_paint_layer" # as Paint Layer...
    IMPORT_LAYER_AS_TRANSPARENCY_MASK = "import_layer_as_transparency_mask" # as Transparency Mask...
    IMPORT_LAYER_AS_FILTER_MASK = "import_layer_as_filter_mask" # as Filter Mask...
    IMPORT_LAYER_AS_SELECTION_MASK = "import_layer_as_selection_mask" # as Selection Mask...
    IMAGE_COLOR = "image_color" # Image Background Colour and Transparency...
    VIEW_GRID = "view_grid" # Show Grid
    VIEW_SNAP_TO_GRID = "view_snap_to_grid" # Snap To Grid
    VIEW_TOGGLE_PAINTING_ASSISTANTS = "view_toggle_painting_assistants" # Show Painting Assistants
    VIEW_TOGGLE_ASSISTANT_PREVIEWS = "view_toggle_assistant_previews" # Show Assistant Previews
    VIEW_TOGGLE_REFERENCE_IMAGES = "view_toggle_reference_images" # Show Reference Images
    MAKE_BRUSH_COLOR_LIGHTER = "make_brush_color_lighter" # Make brush colour lighter
    MAKE_BRUSH_COLOR_DARKER = "make_brush_color_darker" # Make brush colour darker
    MAKE_BRUSH_COLOR_SATURATED = "make_brush_color_saturated" # Make brush colour more saturated
    MAKE_BRUSH_COLOR_DESATURATED = "make_brush_color_desaturated" # Make brush colour more desaturated
    SHIFT_BRUSH_COLOR_CLOCKWISE = "shift_brush_color_clockwise" # Shift brush colour hue clockwise
    SHIFT_BRUSH_COLOR_COUNTER_CLOCKWISE = "shift_brush_color_counter_clockwise" # Shift brush colour hue counter-clockwise
    MAKE_BRUSH_COLOR_REDDER = "make_brush_color_redder" # Make brush colour more red
    MAKE_BRUSH_COLOR_GREENER = "make_brush_color_greener" # Make brush colour more green
    MAKE_BRUSH_COLOR_BLUER = "make_brush_color_bluer" # Make brush colour more blue
    MAKE_BRUSH_COLOR_YELLOWER = "make_brush_color_yellower" # Make brush colour more yellow
    INCREASE_OPACITY = "increase_opacity" # Increase Opacity
    DECREASE_OPACITY = "decrease_opacity" # Decrease Opacity
    INCREASE_FLOW = "increase_flow" # Increase Flow
    DECREASE_FLOW = "decrease_flow" # Decrease Flow
    INCREASE_FADE = "increase_fade" # Increase Fade
    DECREASE_FADE = "decrease_fade" # Decrease Fade
    INCREASE_SCATTER = "increase_scatter" # Increase Scatter
    DECREASE_SCATTER = "decrease_scatter" # Decrease Scatter
    MIRROR_CANVAS = "mirror_canvas" # Mirror View
    MIRROR_CANVAS_AROUND_CURSOR = "mirror_canvas_around_cursor" # Mirror View Around Cursor
    PATTERNS = "patterns" # Patterns
    GRADIENTS = "gradients" # Gradients
    DUAL = "dual" # Choose foreground and background colours
    ERASE_ACTION = "erase_action" # Set eraser mode
    RELOAD_PRESET_ACTION = "reload_preset_action" # Reload Original Preset
    PRESERVE_ALPHA = "preserve_alpha" # Preserve Alpha
    MIRROR_X_HIDE_DECORATIONS = "mirrorX-hideDecorations" # Hide Mirror X Line
    MIRROR_X_LOCK = "mirrorX-lock" # Lock X Line
    MIRROR_X_MOVE_TO_CENTER = "mirrorX-moveToCenter" # Move to Canvas Centre X
    MIRROR_Y_HIDE_DECORATIONS = "mirrorY-hideDecorations" # Hide Mirror Y Line
    MIRROR_Y_LOCK = "mirrorY-lock" # Lock Y Line
    MIRROR_Y_MOVE_TO_CENTER = "mirrorY-moveToCenter" # Move to Canvas Centre Y
    H_MIRROR_ACTION = "hmirror_action" # Horizontal Mirror Tool
    V_MIRROR_ACTION = "vmirror_action" # Vertical Mirror Tool
    NEXT_BLENDING_MODE = "Next Blending Mode" # Next Blending Mode
    PREVIOUS_BLENDING_MODE = "Previous Blending Mode" # Previous Blending Mode
    SELECT_NORMAL_BLENDING_MODE = "Select Normal Blending Mode" # Select Normal Blending Mode
    SELECT_DISSOLVE_BLENDING_MODE = "Select Dissolve Blending Mode" # Select Dissolve Blending Mode
    SELECT_BEHIND_BLENDING_MODE = "Select Behind Blending Mode" # Select Behind Blending Mode
    SELECT_CLEAR_BLENDING_MODE = "Select Clear Blending Mode" # Select Clear Blending Mode
    SELECT_DARKEN_BLENDING_MODE = "Select Darken Blending Mode" # Select Darken Blending Mode
    SELECT_MULTIPLY_BLENDING_MODE = "Select Multiply Blending Mode" # Select Multiply Blending Mode
    SELECT_COLOR_BURN_BLENDING_MODE = "Select Color Burn Blending Mode" # Select Colour Burn Blending Mode
    SELECT_LINEAR_BURN_BLENDING_MODE = "Select Linear Burn Blending Mode" # Select Linear Burn Blending Mode
    SELECT_LIGHTEN_BLENDING_MODE = "Select Lighten Blending Mode" # Select Lighten Blending Mode
    SELECT_SCREEN_BLENDING_MODE = "Select Screen Blending Mode" # Select Screen Blending Mode
    SELECT_COLOR_DODGE_BLENDING_MODE = "Select Color Dodge Blending Mode" # Select Colour Dodge Blending Mode
    SELECT_LINEAR_DODGE_BLENDING_MODE = "Select Linear Dodge Blending Mode" # Select Linear Dodge Blending Mode
    SELECT_OVERLAY_BLENDING_MODE = "Select Overlay Blending Mode" # Select Overlay Blending Mode
    SELECT_HARD_OVERLAY_BLENDING_MODE = "Select Hard Overlay Blending Mode" # Select Hard Overlay Blending Mode
    SELECT_SOFT_LIGHT_BLENDING_MODE = "Select Soft Light Blending Mode" # Select Soft Light Blending Mode
    SELECT_HARD_LIGHT_BLENDING_MODE = "Select Hard Light Blending Mode" # Select Hard Light Blending Mode
    SELECT_VIVID_LIGHT_BLENDING_MODE = "Select Vivid Light Blending Mode" # Select Vivid Light Blending Mode
    SELECT_LINEAR_LIGHT_BLENDING_MODE = "Select Linear Light Blending Mode" # Select Linear Light Blending Mode
    SELECT_PIN_LIGHT_BLENDING_MODE = "Select Pin Light Blending Mode" # Select Pin Light Blending Mode
    SELECT_HARD_MIX_BLENDING_MODE = "Select Hard Mix Blending Mode" # Select Hard Mix Blending Mode
    SELECT_DIFFERENCE_BLENDING_MODE = "Select Difference Blending Mode" # Select Difference Blending Mode
    SELECT_EXCLUSION_BLENDING_MODE = "Select Exclusion Blending Mode" # Select Exclusion Blending Mode
    SELECT_HUE_BLENDING_MODE = "Select Hue Blending Mode" # Select Hue Blending Mode
    SELECT_SATURATION_BLENDING_MODE = "Select Saturation Blending Mode" # Select Saturation Blending Mode
    SELECT_COLOR_BLENDING_MODE = "Select Color Blending Mode" # Select Colour Blending Mode
    SELECT_LUMINOSITY_BLENDING_MODE = "Select Luminosity Blending Mode" # Select Luminosity Blending Mode
    COMPOSITE_ACTIONS = "composite_actions" # Brush composite
    BRUSHSLIDER1 = "brushslider1" # Brush option slider 1
    BRUSHSLIDER2 = "brushslider2" # Brush option slider 2
    BRUSHSLIDER3 = "brushslider3" # Brush option slider 3
    BRUSHSLIDER4 = "brushslider4" # Brush option slider 4
    NEXT_FAVORITE_PRESET = "next_favorite_preset" # Next Favourite Preset
    PREVIOUS_FAVORITE_PRESET = "previous_favorite_preset" # Previous Favourite Preset
    PREVIOUS_PRESET = "previous_preset" # Switch to Previous Preset
    SHOW_BRUSH_PRESETS = "show_brush_presets" # Show Brush Presets
    MIRROR_ACTIONS = "mirror_actions" # Mirror
    WORKSPACES = "workspaces" # Workspaces
    SHOW_BRUSH_EDITOR = "show_brush_editor" # Show Brush Editor
    DISABLE_PRESSURE = "disable_pressure" # Use Pen Pressure
    PAINTOPS = "paintops" # Painter's Tools
    CHOOSE_FOREGROUND_COLOR = "chooseForegroundColor" # Open Foreground colour selector
    CHOOSE_BACKGROUND_COLOR = "chooseBackgroundColor" # Open Background colour selector
    IMAGESIZE = "imagesize" # Scale Image To New Size...
    CANVASSIZE = "canvassize" # Resize Canvas...
    LAYERSIZE = "layersize" # Scale Layer to new Size...
    SCALE_ALL_LAYERS = "scaleAllLayers" # Scale All Layers to new Size...
    SELECTIONSCALE = "selectionscale" # Scale...
    BUGINFO = "buginfo" # Show Krita log for bug reports.
    SYSINFO = "sysinfo" # Show system information for bug reports.
    CRASHLOG = "crashlog" # Show crash log for bug reports.
    CLONES_ARRAY = "clones_array" # Clones Array...
    COLORRANGE = "colorrange" # Select from Colour Range...
    SELECTOPAQUE = "selectopaque" # Select Opaque (Replace)
    SELECTOPAQUE_ADD = "selectopaque_add" # Select Opaque (Add)
    SELECTOPAQUE_SUBTRACT = "selectopaque_subtract" # Select Opaque (Subtract)
    SELECTOPAQUE_INTERSECT = "selectopaque_intersect" # Select Opaque (Intersect)
    IMAGECOLORSPACECONVERSION = "imagecolorspaceconversion" # Convert Image Colour Space...
    LAYERCOLORSPACECONVERSION = "layercolorspaceconversion" # Convert Layer Colour Space...
    DBEXPLORER = "dbexplorer" # Explore Resources Cache Database...
    IMAGESPLIT = "imagesplit" # Image Split 
    LAYER_GROUP_SWITCHER_PREVIOUS = "LayerGroupSwitcher/previous" # Move into previous group
    LAYER_GROUP_SWITCHER_NEXT = "LayerGroupSwitcher/next" # Move into next group
    LAYERSPLIT = "layersplit" # Split Layer...
    EDIT_LAYER_META_DATA = "EditLayerMetaData" # Edit metadata...
    GROWSELECTION = "growselection" # Grow Selection...
    SHRINKSELECTION = "shrinkselection" # Shrink Selection...
    BORDERSELECTION = "borderselection" # Border Selection...
    FEATHERSELECTION = "featherselection" # Feather Selection...
    SMOOTHSELECTION = "smoothselection" # Smooth
    OFFSETIMAGE = "offsetimage" # Offset Image...
    OFFSETLAYER = "offsetlayer" # Offset Layer...
    MANAGE_BUNDLES = "manage_bundles" # Manage Resource Libraries...
    MANAGE_RESOURCES = "manage_resources" # Manage Resources...
    ROTATEIMAGE = "rotateimage" # Rotate Image...
    ROTATE_IMAGE_C_W90 = "rotateImageCW90" # Rotate Image 90° to the Right
    ROTATE_IMAGE180 = "rotateImage180" # Rotate Image 180°
    ROTATE_IMAGE_C_C_W90 = "rotateImageCCW90" # Rotate Image 90° to the Left
    MIRROR_IMAGE_HORIZONTAL = "mirrorImageHorizontal" # Mirror Image Horizontally
    MIRROR_IMAGE_VERTICAL = "mirrorImageVertical" # Mirror Image Vertically
    ROTATELAYER = "rotatelayer" # Rotate Layer...
    ROTATE_LAYER180 = "rotateLayer180" # Rotate Layer 180°
    ROTATE_LAYER_C_W90 = "rotateLayerCW90" # Rotate Layer 90° to the Right
    ROTATE_LAYER_C_C_W90 = "rotateLayerCCW90" # Rotate Layer 90° to the Left
    ROTATE_ALL_LAYERS = "rotateAllLayers" # Rotate All Layers...
    ROTATE_ALL_LAYERS_C_W90 = "rotateAllLayersCW90" # Rotate All Layers 90° to the Right
    ROTATE_ALL_LAYERS_C_C_W90 = "rotateAllLayersCCW90" # Rotate All Layers 90° to the Left
    ROTATE_ALL_LAYERS180 = "rotateAllLayers180" # Rotate All Layers 180°
    SEPARATE = "separate" # Separate Image...
    SHEARIMAGE = "shearimage" # Shear Image...
    SHEARLAYER = "shearlayer" # Shear Layer...
    SHEAR_ALL_LAYERS = "shearAllLayers" # Shear All Layers...
    WAVELETDECOMPOSE = "waveletdecompose" # Wavelet Decompose ...
    INCREASE_BRUSH_SIZE = "increase_brush_size" # Increase Brush Size
    DECREASE_BRUSH_SIZE = "decrease_brush_size" # Decrease Brush Size
    SELECTION_TOOL_MODE_ADD = "selection_tool_mode_add" # Selection Mode: Add
    SELECTION_TOOL_MODE_REPLACE = "selection_tool_mode_replace" # Selection Mode: Replace
    SELECTION_TOOL_MODE_SUBTRACT = "selection_tool_mode_subtract" # Selection Mode: Subtract
    SELECTION_TOOL_MODE_INTERSECT = "selection_tool_mode_intersect" # Selection Mode: Intersect
    UNDO_POLYGON_SELECTION = "undo_polygon_selection" # Undo Polygon Selection Points
    OBJECT_ORDER_FRONT = "object_order_front" # Bring to Front
    OBJECT_ORDER_RAISE = "object_order_raise" # Raise
    OBJECT_ORDER_LOWER = "object_order_lower" # Lower
    OBJECT_ORDER_BACK = "object_order_back" # Send to Back
    OBJECT_TRANSFORM_ROTATE_90_CW = "object_transform_rotate_90_cw" # Rotate 90° CW
    OBJECT_TRANSFORM_ROTATE_90_CCW = "object_transform_rotate_90_ccw" # Rotate 90° ACW
    OBJECT_TRANSFORM_ROTATE_180 = "object_transform_rotate_180" # Rotate 180°
    OBJECT_TRANSFORM_MIRROR_HORIZONTALLY = "object_transform_mirror_horizontally" # Mirror Horizontally
    OBJECT_TRANSFORM_MIRROR_VERTICALLY = "object_transform_mirror_vertically" # Mirror Vertically
    OBJECT_TRANSFORM_RESET = "object_transform_reset" # Reset Transformations
    SET_NO_BRUSH_SMOOTHING = "set_no_brush_smoothing" # Brush Smoothing: Disabled
    SET_SIMPLE_BRUSH_SMOOTHING = "set_simple_brush_smoothing" # Brush Smoothing: Basic
    SET_WEIGHTED_BRUSH_SMOOTHING = "set_weighted_brush_smoothing" # Brush Smoothing: Weighted
    SET_STABILIZER_BRUSH_SMOOTHING = "set_stabilizer_brush_smoothing" # Brush Smoothing: Stabiliser
    TOGGLE_ASSISTANT = "toggle_assistant" # Toggle Snap To Assistants
    CALLIGRAPHY_INCREASE_WIDTH = "calligraphy_increase_width" # Calligraphy: increase width
    CALLIGRAPHY_DECREASE_WIDTH = "calligraphy_decrease_width" # Calligraphy: decrease width
    CALLIGRAPHY_INCREASE_ANGLE = "calligraphy_increase_angle" # Calligraphy: increase angle
    CALLIGRAPHY_DECREASE_ANGLE = "calligraphy_decrease_angle" # Calligraphy: decrease angle
    OBJECT_ALIGN_HORIZONTAL_LEFT = "object_align_horizontal_left" # Align Left
    OBJECT_ALIGN_HORIZONTAL_CENTER = "object_align_horizontal_center" # Horizontally Centre
    OBJECT_ALIGN_HORIZONTAL_RIGHT = "object_align_horizontal_right" # Align Right
    OBJECT_ALIGN_VERTICAL_TOP = "object_align_vertical_top" # Align Top
    OBJECT_ALIGN_VERTICAL_CENTER = "object_align_vertical_center" # Vertically Centre
    OBJECT_ALIGN_VERTICAL_BOTTOM = "object_align_vertical_bottom" # Align Bottom
    OBJECT_DISTRIBUTE_HORIZONTAL_LEFT = "object_distribute_horizontal_left" # Distribute Left
    OBJECT_DISTRIBUTE_HORIZONTAL_CENTER = "object_distribute_horizontal_center" # Distribute Centres Horizontally
    OBJECT_DISTRIBUTE_HORIZONTAL_RIGHT = "object_distribute_horizontal_right" # Distribute Right
    OBJECT_DISTRIBUTE_HORIZONTAL_GAPS = "object_distribute_horizontal_gaps" # Distribute Horizontal Gap
    OBJECT_DISTRIBUTE_VERTICAL_TOP = "object_distribute_vertical_top" # Distribute Top
    OBJECT_DISTRIBUTE_VERTICAL_CENTER = "object_distribute_vertical_center" # Distribute Centres Vertically
    OBJECT_DISTRIBUTE_VERTICAL_BOTTOM = "object_distribute_vertical_bottom" # Distribute Bottom
    OBJECT_DISTRIBUTE_VERTICAL_GAPS = "object_distribute_vertical_gaps" # Distribute Vertical Gap
    OBJECT_GROUP = "object_group" # Group
    OBJECT_UNGROUP = "object_ungroup" # Ungroup
    OBJECT_UNITE = "object_unite" # Unite
    OBJECT_INTERSECT = "object_intersect" # Intersect
    OBJECT_SUBTRACT = "object_subtract" # Subtract
    OBJECT_SPLIT = "object_split" # Split
    PATH_TOOL = "PathTool" # Edit Shapes Tool
    PATHPOINT_CORNER = "pathpoint-corner" # Corner point
    PATHPOINT_SMOOTH = "pathpoint-smooth" # Smooth point
    PATHPOINT_SYMMETRIC = "pathpoint-symmetric" # Symmetric Point
    PATHPOINT_CURVE = "pathpoint-curve" # Make curve point
    PATHPOINT_LINE = "pathpoint-line" # Make line point
    PATHSEGMENT_LINE = "pathsegment-line" # Segment to Line
    PATHSEGMENT_CURVE = "pathsegment-curve" # Segment to Curve
    PATHPOINT_INSERT = "pathpoint-insert" # Insert point
    PATHPOINT_REMOVE = "pathpoint-remove" # Remove point
    PATH_BREAK_POINT = "path-break-point" # Break at point
    PATH_BREAK_SEGMENT = "path-break-segment" # Break at segment
    PATHPOINT_JOIN = "pathpoint-join" # Join with segment
    PATHPOINT_MERGE = "pathpoint-merge" # Merge points
    CONVERT_TO_PATH = "convert-to-path" # To Path
    MOVETOOL_MOVE_UP = "movetool-move-up" # Move up
    MOVETOOL_MOVE_DOWN = "movetool-move-down" # Move down
    MOVETOOL_MOVE_LEFT = "movetool-move-left" # Move left
    MOVETOOL_MOVE_RIGHT = "movetool-move-right" # Move right
    MOVETOOL_MOVE_UP_MORE = "movetool-move-up-more" # Move up more
    MOVETOOL_MOVE_DOWN_MORE = "movetool-move-down-more" # Move down more
    MOVETOOL_MOVE_LEFT_MORE = "movetool-move-left-more" # Move left more
    MOVETOOL_MOVE_RIGHT_MORE = "movetool-move-right-more" # Move right more
    MOVETOOL_SHOW_COORDINATES = "movetool-show-coordinates" # Show Coordinates
    ADD_SCALAR_KEYFRAMES = "add_scalar_keyframes" # Add scalar keyframes
    REMOVE_SCALAR_KEYFRAME = "remove_scalar_keyframe" # Remove scalar keyframe
    INTERPOLATION_CONSTANT = "interpolation_constant" # Hold constant value. No interpolation.
    INTERPOLATION_LINEAR = "interpolation_linear" # Linear interpolation.
    INTERPOLATION_BEZIER = "interpolation_bezier" # Bezier curve interpolation.
    TANGENTS_SHARP = "tangents_sharp" # Sharp interpolation tangents.
    TANGENTS_SMOOTH = "tangents_smooth" # Smooth interpolation tangents.
    ZOOM_TO_FIT_RANGE = "zoom_to_fit_range" # Zoom view to fit channel range.
    ZOOM_TO_FIT_CURVE = "zoom_to_fit_curve" # Zoom view to fit curve.
    DROP_FRAMES = "drop_frames" # Drop Frames
    SHOW_GLOBAL_SELECTION_MASK = "show-global-selection-mask" # Show Global Selection Mask
    RENAME_CURRENT_LAYER = "RenameCurrentLayer" # Rename current layer
    LAYER_PROPERTIES = "layer_properties" # Properties...
    REMOVE_LAYER = "remove_layer" # Remove Layer
    MOVE_LAYER_UP = "move_layer_up" # Move Layer or Mask Up
    MOVE_LAYER_DOWN = "move_layer_down" # Move Layer or Mask Down
    SET_COPY_FROM = "set-copy-from" # Set Copy From...
    TOGGLE_LAYER_SOLOING = "toggle_layer_soloing" # Toggle Layer Soloing
    TOGGLE_ONION_SKIN = "toggle_onion_skin" # Toggle onion skin
    CREATE_SNAPSHOT = "create_snapshot" # Create Snapshot
    SWITCHTO_SNAPSHOT = "switchto_snapshot" # Switch to Selected Snapshot
    REMOVE_SNAPSHOT = "remove_snapshot" # Remove Selected Snapshot
    INSERT_COLUMN_LEFT = "insert_column_left" # Insert Column Left
    INSERT_COLUMN_RIGHT = "insert_column_right" # Insert Column Right
    INSERT_MULTIPLE_COLUMNS = "insert_multiple_columns" # Insert Multiple Columns
    REMOVE_COLUMNS_AND_PULL = "remove_columns_and_pull" # Remove Column and Pull
    REMOVE_COLUMNS = "remove_columns" # Remove Column
    INSERT_HOLD_COLUMN = "insert_hold_column" # Insert Hold Column
    INSERT_MULTIPLE_HOLD_COLUMNS = "insert_multiple_hold_columns" # Insert Multiple Hold Columns
    REMOVE_HOLD_COLUMN = "remove_hold_column" # Remove Hold Column
    REMOVE_MULTIPLE_HOLD_COLUMNS = "remove_multiple_hold_columns" # Remove Multiple Hold Columns
    MIRROR_COLUMNS = "mirror_columns" # Mirror Columns
    CLEAR_ANIMATION_CACHE = "clear_animation_cache" # Clear Cache
    COPY_COLUMNS_TO_CLIPBOARD = "copy_columns_to_clipboard" # Copy Columns
    CUT_COLUMNS_TO_CLIPBOARD = "cut_columns_to_clipboard" # Cut Columns
    PASTE_COLUMNS_FROM_CLIPBOARD = "paste_columns_from_clipboard" # Paste Columns
    ADD_BLANK_FRAME = "add_blank_frame" # Create Blank Frame
    ADD_DUPLICATE_FRAME = "add_duplicate_frame" # Create Duplicate Frame
    INSERT_KEYFRAME_LEFT = "insert_keyframe_left" # Insert Keyframe Left
    INSERT_KEYFRAME_RIGHT = "insert_keyframe_right" # Insert Keyframe Right
    INSERT_MULTIPLE_KEYFRAMES = "insert_multiple_keyframes" # Insert Multiple Keyframes
    REMOVE_FRAMES_AND_PULL = "remove_frames_and_pull" # Remove Frame and Pull
    REMOVE_FRAMES = "remove_frames" # Remove Keyframe
    INSERT_HOLD_FRAME = "insert_hold_frame" # Insert Hold Frame
    INSERT_MULTIPLE_HOLD_FRAMES = "insert_multiple_hold_frames" # Insert Multiple Hold Frames
    REMOVE_HOLD_FRAME = "remove_hold_frame" # Remove Hold Frame
    REMOVE_MULTIPLE_HOLD_FRAMES = "remove_multiple_hold_frames" # Remove Multiple Hold Frames
    MIRROR_FRAMES = "mirror_frames" # Mirror Frames
    COPY_FRAMES = "copy_frames" # Copy Keyframes
    COPY_FRAMES_AS_CLONES = "copy_frames_as_clones" # Clone Keyframes
    MAKE_CLONES_UNIQUE = "make_clones_unique" # Make Unique
    CUT_FRAMES = "cut_frames" # Cut Keyframes
    PASTE_FRAMES = "paste_frames" # Paste Keyframes
    SET_START_TIME = "set_start_time" # Set Start Time
    SET_END_TIME = "set_end_time" # Set End Time
    UPDATE_PLAYBACK_RANGE = "update_playback_range" # Update Playback Range
    TOGGLE_PLAYBACK = "toggle_playback" # Play / pause animation
    STOP_PLAYBACK = "stop_playback" # Stop animation
    PREVIOUS_FRAME = "previous_frame" # Previous Frame
    NEXT_FRAME = "next_frame" # Next Frame
    PREVIOUS_KEYFRAME = "previous_keyframe" # Previous Keyframe
    NEXT_KEYFRAME = "next_keyframe" # Next Keyframe
    PREVIOUS_MATCHING_KEYFRAME = "previous_matching_keyframe" # Previous Matching Keyframe
    NEXT_MATCHING_KEYFRAME = "next_matching_keyframe" # Next Matching Keyframe
    PREVIOUS_UNFILTERED_KEYFRAME = "previous_unfiltered_keyframe" # Previous Unfiltered Keyframe
    NEXT_UNFILTERED_KEYFRAME = "next_unfiltered_keyframe" # Next Unfiltered Keyframe
    AUTO_KEY = "auto_key" # Auto Frame Mode
    FILE_NEW = "file_new" # New...
    FILE_OPEN = "file_open" # Open...
    FILE_QUIT = "file_quit" # Quit
    OPTIONS_CONFIGURE_TOOLBARS = "options_configure_toolbars" # Configure Toolbars...
    FULLSCREEN = "fullscreen" # Full Screen Mode
    FILE_OPEN_RECENT = "file_open_recent" # Open Recent
    FILE_SAVE = "file_save" # Save
    FILE_SAVE_AS = "file_save_as" # Save As...
    EDIT_UNDO = "edit_undo" # Undo
    EDIT_REDO = "edit_redo" # Redo
    FILE_IMPORT_ANIMATION = "file_import_animation" # Import animation frames...
    FILE_IMPORT_VIDEO_ANIMATION = "file_import_video_animation" # Import video animation...
    RENDER_ANIMATION = "render_animation" # Render Animation...
    RENDER_ANIMATION_AGAIN = "render_animation_again" # Render Animation Again
    FILE_CLOSE_ALL = "file_close_all" # Close All
    FILE_IMPORT_FILE = "file_import_file" # Open existing Document as Untitled Document...
    FILE_EXPORT_FILE = "file_export_file" # Export...
    FILE_EXPORT_ADVANCED = "file_export_advanced" # Export Advanced...
    FILE_DOCUMENTINFO = "file_documentinfo" # Document Information
    THEME_MENU = "theme_menu" # Themes
    VIEW_TOGGLEDOCKERS = "view_toggledockers" # Show Dockers
    RESET_CONFIGURATIONS = "reset_configurations" # Reset All Settings
    VIEW_DETACHED_CANVAS = "view_detached_canvas" # Detach canvas
    VIEW_TOGGLEDOCKERTITLEBARS = "view_toggledockertitlebars" # Show Docker Titlebars
    SETTINGS_DOCKERS_MENU = "settings_dockers_menu" # Dockers
    WINDOW = "window" # Window
    STYLE_MENU = "style_menu" # Styles
    WINDOWS_CASCADE = "windows_cascade" # Cascade
    WINDOWS_TILE = "windows_tile" # Tile
    WINDOWS_NEXT = "windows_next" # Next
    WINDOWS_PREVIOUS = "windows_previous" # Previous
    VIEW_NEWWINDOW = "view_newwindow" # New Window
    FILE_CLOSE = "file_close" # Close
    FILE_SESSIONS = "file_sessions" # Sessions...
    COMMAND_BAR_OPEN = "command_bar_open" # Search Actions
    OPTIONS_CONFIGURE = "options_configure" # Configure Krita...
    EXPANDING_SPACER_0 = "expanding_spacer_0" # Expanding Spacer
    EXPANDING_SPACER_1 = "expanding_spacer_1" # Expanding Spacer
    HELP_CONTENTS = "help_contents" # Krita Handbook
    HELP_REPORT_BUG = "help_report_bug" # Report Bug...
    SWITCH_APPLICATION_LANGUAGE = "switch_application_language" # Switch Application Language...
    HELP_ABOUT_APP = "help_about_app" # About Krita
    HELP_ABOUT_KDE = "help_about_kde" # About KDE
    RECORDER_RECORD_TOGGLE = "recorder_record_toggle" # Record Timelapse
    RECORDER_EXPORT = "recorder_export" # Export Timelapse...
    MAIN_TOOL_BAR = "mainToolBar" # Hide File Toolbar
    BRUSHES_AND_STUFF = "BrushesAndStuff" # Hide Brushes and Stuff Toolbar

    # Built-in Scripts (The ones that make sesne to include)
    COLOR_SPACE = "color_space" # Colour Space
    DOCUMENT_TOOLS = "document_tools" # Document Tools
    EXPORT_LAYERS = "export_layers" # Export Layers
    FILTER_MANAGER = "filter_manager" # Filter Manager
    PLUGIN_IMPORTER_FILE = "plugin_importer_file" # Import Python Plugin from File...
    PLUGIN_IMPORTER_WEB = "plugin_importer_web" # Import Python Plugin from Web...
    PYTHON_SCRIPTER = "python_scripter" # Scripter
    TEN_SCRIPTS = "ten_scripts" # Ten Scripts
    EXECUTE_SCRIPT_1 = "execute_script_1" # Execute Script 1
    EXECUTE_SCRIPT_2 = "execute_script_2" # Execute Script 2
    EXECUTE_SCRIPT_3 = "execute_script_3" # Execute Script 3
    EXECUTE_SCRIPT_4 = "execute_script_4" # Execute Script 4
    EXECUTE_SCRIPT_5 = "execute_script_5" # Execute Script 5
    EXECUTE_SCRIPT_6 = "execute_script_6" # Execute Script 6
    EXECUTE_SCRIPT_7 = "execute_script_7" # Execute Script 7
    EXECUTE_SCRIPT_8 = "execute_script_8" # Execute Script 8
    EXECUTE_SCRIPT_9 = "execute_script_9" # Execute Script 9
    EXECUTE_SCRIPT_10 = "execute_script_10" # Execute Script 10

    # ShortcutComposer actions (The ones that make sense to use this way)
    RELOAD_SHORTCUT_COMPOSER = "Reload Shortcut Composer" # Reload Shortcut Composer
    CONFIGURE_SHORTCUT_COMPOSER = "Configure Shortcut Composer" # Configure Shortcut Composer

    def activate(self):
        Api.instance().action(self.value).trigger()

    @property
    def icon(self) -> QIcon:
        """Return the icon of this tool."""
        icon_name = _ICON_NAME_MAP.get(self, "edit-delete")
        return Api.instance().icon(icon_name)


_ICON_NAME_MAP = {
}
"""Maps actions to names of their icons."""
