from enum import Enum


class Tool(Enum):
    freehand_brush = "KritaShape/KisToolBrush"
    freehand_selection = "KisToolSelectOutline"
    gradient = "KritaFill/KisToolGradient"
    line = "KritaShape/KisToolLine"
    transform = "KisToolTransform"
    move = "KritaTransform/KisToolMove"
    rectangular_selection = "KisToolSelectRectangular"
    contiquous_selection = "KisToolSelectContiguous"
    reference = "ToolReferenceImages"
    crop = "KisToolCrop"
    bezier_path = "KisToolPath"
    freehand_path = "KisToolPencil"
    polyline = "KisToolPolyline"
    shape_select = "InteractionTool"
    assistants = "KisAssistantTool"
    color_sampler = "KritaSelected/KisToolColorSampler"
    polygon = "KisToolPolygon"
    measurement = "KritaShape/KisToolMeasure"
    text = "SvgTextTool"
    ellipse = "KritaShape/KisToolEllipse"
    fill = "KritaFill/KisToolFill"
    bezier_selection = "KisToolSelectPath"
    dynamic_brush = "KritaShape/KisToolDyna"
    rectangle = "KritaShape/KisToolRectangle"
    pan = "PanTool"
    multi_brush = "KritaShape/KisToolMultiBrush"
    edit_shapes = "PathTool"
    eliptical_selection = "KisToolSelectElliptical"
    smart_patch = "KritaShape/KisToolSmartPatch"
    colorize_mask = "KritaShape/KisToolLazyBrush"
    similar_color_selection = "KisToolSelectSimilar"
    zoom = "ZoomTool"
    magnetic_selection = "KisToolSelectMagnetic"
    calligraphy = "KarbonCalligraphyTool"
    polygonal_selection = "KisToolSelectPolygonal"
