<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Scripts">

    <Actions category="Scripts">
        <text>Shortcut Composer: Temporary Tools</text>

        <!-- .................................... -->
        <!-- ...Insert your action definitions... -->
        <!-- ......in any of the categories...... -->
        <!-- .................................... -->

        <Action name="Temporary move tool">
        <activationFlags>1</activationFlags>
        </Action>

        <Action name="Temporary eraser">
        <activationFlags>1</activationFlags>
        </Action>

        <Action name="Temporary preserve alpha">
        <activationFlags>1</activationFlags>
        </Action>

    </Actions>
    <Actions category="Scripts">
        <text>Shortcut Composer: Canvas Previews</text>

        <Action name="Preview current layer visibility">
        <activationFlags>1</activationFlags>
        </Action>

        <Action name="Preview projection below">
        <activationFlags>1</activationFlags>
        </Action>

    </Actions>
    <Actions category="Scripts">
        <text>Shortcut Composer: Multiple Assignments</text>

        <Action name="Cycle painting opacity">
        <activationFlags>1</activationFlags>
        </Action>

        <Action name="Cycle selection tools">
        <activationFlags>1</activationFlags>
        </Action>

    </Actions>
    <Actions category="Scripts">
        <text>Shortcut Composer: Mouse Trackers</text>

        <Action name="Scroll undo stack">
        <activationFlags>1</activationFlags>
        </Action>

        <Action name="Scroll isolated layers">
        <activationFlags>1</activationFlags>
        </Action>

        <Action name="Scroll timeline or animated layers">
        <activationFlags>1</activationFlags>
        </Action>

        <Action name="Scroll brush size or opacity">
        <activationFlags>1</activationFlags>
        </Action>

        <Action name="Scroll canvas zoom or rotation">
        <activationFlags>1</activationFlags>
        </Action>

    </Actions>
    <Actions category="Scripts">
        <text>Shortcut Composer: Pie Menus</text>

        <Action name="Pick misc tools">
        <activationFlags>1</activationFlags>
        </Action>

        <Action name="Pick painting blending modes">
        <activationFlags>1</activationFlags>
        </Action>

        <Action name="Pick transform tool modes">
        <activationFlags>1</activationFlags>
        </Action>

        <Action name="Pick brush presets (red)">
        <activationFlags>1</activationFlags>
        </Action>

        <Action name="Pick brush presets (green)">
        <activationFlags>1</activationFlags>
        </Action>

        <Action name="Pick brush presets (blue)">
        <activationFlags>1</activationFlags>
        </Action>

    </Actions>
    <Actions category="Scripts">
        <text>Shortcut Composer: Utilities</text>

        <Action name="Configure Shortcut Composer">
        <activationFlags>0</activationFlags>
        </Action>

        <Action name="Reload Shortcut Composer">
        <activationFlags>0</activationFlags>
        </Action>
        
        <Action name="Transform tool: free">
        <activationFlags>1</activationFlags>
        <activationConditions>1</activationConditions>
        </Action>
        
        <Action name="Transform tool: perspective">
        <activationFlags>1</activationFlags>
        <activationConditions>1</activationConditions>
        </Action>

        <Action name="Transform tool: warp">
        <activationFlags>1</activationFlags>
        <activationConditions>1</activationConditions>
        </Action>

        <Action name="Transform tool: cage">
        <activationFlags>1</activationFlags>
        <activationConditions>1</activationConditions>
        </Action>

        <Action name="Transform tool: liquify">
        <activationFlags>1</activationFlags>
        <activationConditions>1</activationConditions>
        </Action>

        <Action name="Transform tool: mesh">
        <activationFlags>1</activationFlags>
        <activationConditions>1</activationConditions>
        </Action>

    </Actions>
</ActionCollection>
