<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Scripts">

    <Actions category="Scripts">
        <text>Shortcut Composer: Temporary Tools</text>

        <!-- .................................... -->
        <!-- ...Insert your action definitions... -->
        <!-- ......in any of the categories...... -->
        <!-- .................................... -->

        <Action name="Temporary move tool">
        <activationFlags>1</activationFlags>
        <icon>krita_tool_move</icon>
        </Action>

        <Action name="Temporary eraser">
        <activationFlags>1</activationFlags>
        <icon>draw-eraser</icon>
        </Action>

        <Action name="Temporary preserve alpha">
        <activationFlags>1</activationFlags>
        <icon>bar-transparency-unlocked</icon>
        </Action>

    </Actions>
    <Actions category="Scripts">
        <text>Shortcut Composer: Canvas Previews</text>

        <Action name="Preview current layer visibility">
        <activationFlags>1</activationFlags>
        <icon>current-layer</icon>
        </Action>

        <Action name="Preview projection below">
        <activationFlags>1</activationFlags>
        <icon>all-layers</icon>
        </Action>

    </Actions>
    <Actions category="Scripts">
        <text>Shortcut Composer: Multiple Assignments</text>

        <Action name="Cycle painting opacity">
        <activationFlags>1</activationFlags>
        <icon>opacity-increase</icon>
        </Action>

        <Action name="Cycle selection tools">
        <activationFlags>1</activationFlags>
        <icon>selectionMask</icon>
        </Action>

    </Actions>
    <Actions category="Scripts">
        <text>Shortcut Composer: Mouse Trackers</text>

        <Action name="Scroll undo stack">
        <activationFlags>1</activationFlags>
        <icon>edit-undo</icon>
        </Action>

        <Action name="Scroll isolated layers">
        <activationFlags>1</activationFlags>
        <icon>all-layers</icon>
        </Action>

        <Action name="Scroll timeline or animated layers">
        <activationFlags>1</activationFlags>
        <icon>addduplicateframe</icon>
        </Action>

        <Action name="Scroll brush size or opacity">
        <activationFlags>1</activationFlags>
        <icon>brushsize-increase</icon>
        </Action>

        <Action name="Scroll canvas zoom or rotation">
        <activationFlags>1</activationFlags>
        <icon>zoom-original</icon>
        </Action>

    </Actions>
    <Actions category="Scripts">
        <text>Shortcut Composer: Pie Menus</text>

        <Action name="Pick misc tools">
        <activationFlags>1</activationFlags>
        <icon>krita_tool_grid</icon>
        </Action>

        <Action name="Activate krita action (red)">
        <activationFlags>1</activationFlags>
        <icon>palette-edit</icon>
        </Action>

        <Action name="Activate krita action (green)">
        <activationFlags>1</activationFlags>
        <icon>palette-edit</icon>
        </Action>

        <Action name="Activate krita action (blue)">
        <activationFlags>1</activationFlags>
        <icon>palette-edit</icon>
        </Action>

        <Action name="Pick painting blending modes">
        <activationFlags>1</activationFlags>
        <icon>format-text-bold</icon>
        </Action>

        <Action name="Pick transform tool modes">
        <activationFlags>1</activationFlags>
        <icon>krita_tool_transform</icon>
        </Action>

        <Action name="Pick brush presets (red)">
        <activationFlags>1</activationFlags>
        <icon>config-popup-palette</icon>
        </Action>

        <Action name="Pick brush presets (green)">
        <activationFlags>1</activationFlags>
        <icon>config-popup-palette</icon>
        </Action>

        <Action name="Pick brush presets (blue)">
        <activationFlags>1</activationFlags>
        <icon>config-popup-palette</icon>
        </Action>

        <Action name="Pick local brush presets">
        <activationFlags>1</activationFlags>
        <icon>config-popup-palette</icon>
        </Action>

        <Action name="Create painting layer with blending mode">
        <activationFlags>1</activationFlags>
        <icon>addlayer</icon>
        </Action>

    </Actions>
    <Actions category="Scripts">
        <text>Shortcut Composer: Rotation Selectors</text>

        <Action name="Rotate canvas">
        <activationFlags>1</activationFlags>
        <icon>transform_icons_rotate_cw</icon>
        </Action>

        <Action name="Rotate brush">
        <activationFlags>1</activationFlags>
        <icon>transform_icons_rotate_ccw</icon>
        </Action>

    </Actions>
    <Actions category="Scripts">
        <text>Shortcut Composer: Utilities</text>

        <Action name="Configure Shortcut Composer">
        <activationFlags>0</activationFlags>
        <icon>configure</icon>
        </Action>

        <Action name="Transform tool: free">
        <activationFlags>1</activationFlags>
        <activationConditions>1</activationConditions>
        <icon>krita_tool_transform</icon>
        </Action>

        <Action name="Transform tool: perspective">
        <activationFlags>1</activationFlags>
        <activationConditions>1</activationConditions>
        <icon>transform_icons_perspective</icon>
        </Action>

        <Action name="Transform tool: warp">
        <activationFlags>1</activationFlags>
        <activationConditions>1</activationConditions>
        <icon>transform_icons_warp</icon>
        </Action>

        <Action name="Transform tool: cage">
        <activationFlags>1</activationFlags>
        <activationConditions>1</activationConditions>
        <icon>transform_icons_cage</icon>
        </Action>

        <Action name="Transform tool: liquify">
        <activationFlags>1</activationFlags>
        <activationConditions>1</activationConditions>
        <icon>transform_icons_liquify_main</icon>
        </Action>

        <Action name="Transform tool: mesh">
        <activationFlags>1</activationFlags>
        <activationConditions>1</activationConditions>
        <icon>transform_icons_mesh</icon>
        </Action>

    </Actions>
</ActionCollection>
