<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Scripts">
    <Actions category="Scripts">
        <text>Shortcut Composer Utilities</text>

        <Action name="Shortcut composer settings">
        <text>Shortcut composer settings</text>
        <activationFlags>1</activationFlags>
        <activationConditions>1</activationConditions>
        </Action>

        <Action name="Reload shortcut composer">
        <text>Reload shortcut composer</text>
        <activationFlags>1</activationFlags>
        <activationConditions>1</activationConditions>
        </Action>
        
        <Action name="Transform tool: free">
        <text>Transform tool: free</text>
        <activationFlags>1</activationFlags>
        <activationConditions>1</activationConditions>
        </Action>
        
        <Action name="Transform tool: perspective">
        <text>Transform tool: perspective</text>
        <activationFlags>1</activationFlags>
        <activationConditions>1</activationConditions>
        </Action>

        <Action name="Transform tool: warp">
        <text>Transform tool: warp</text>
        <activationFlags>1</activationFlags>
        <activationConditions>1</activationConditions>
        </Action>

        <Action name="Transform tool: cage">
        <text>Transform tool: cage</text>
        <activationFlags>1</activationFlags>
        <activationConditions>1</activationConditions>
        </Action>

        <Action name="Transform tool: liquify">
        <text>Transform tool: liquify</text>
        <activationFlags>1</activationFlags>
        <activationConditions>1</activationConditions>
        </Action>

        <Action name="Transform tool: mesh">
        <text>Transform tool: mesh</text>
        <activationFlags>1</activationFlags>
        <activationConditions>1</activationConditions>
        </Action>

    </Actions>
</ActionCollection>
