<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Scripts">
    <Actions category="Scripts">
        <text>Shortcut Composer</text>

        <Action name="Scroll isolated layers">
        <text>Scroll isolated layers</text>
        <activationFlags>1</activationFlags>
        <activationConditions>1</activationConditions>
        </Action>

        <Action name="Scroll undo stack">
        <text>Scroll undo stack</text>
        <activationFlags>1</activationFlags>
        <activationConditions>1</activationConditions>
        </Action>

        <Action name="Scroll timeline or animated layers">
        <text>Scroll timeline or animated layers</text>
        <activationFlags>1</activationFlags>
        <activationConditions>1</activationConditions>
        </Action>

        <Action name="Scroll brush size or opacity">
        <text>Scroll brush size or opacity</text>
        <activationFlags>1</activationFlags>
        <activationConditions>1</activationConditions>
        </Action>

        <Action name="Cycle brush presets">
        <text>Cycle brush presets</text>
        <activationFlags>1</activationFlags>
        <activationConditions>1</activationConditions>
        </Action>

        <Action name="Preview current layer visibility">
        <text>Preview current layer visibility</text>
        <activationFlags>1</activationFlags>
        <activationConditions>1</activationConditions>
        </Action>

        <Action name="Preview projection below">
        <text>Preview projection below</text>
        <activationFlags>1</activationFlags>
        <activationConditions>1</activationConditions>
        </Action>

        <Action name="Temporary eraser">
        <text>Temporary eraser</text>
        <activationFlags>1</activationFlags>
        <activationConditions>1</activationConditions>
        </Action>

        <Action name="Temporary preserve alpha">
        <text>Temporary preserve alpha</text>
        <activationFlags>1</activationFlags>
        <activationConditions>1</activationConditions>
        </Action>

        <Action name="Temporary move tool">
        <text>Temporary move tool</text>
        <activationFlags>1</activationFlags>
        <activationConditions>1</activationConditions>
        </Action>

        <Action name="Temporary transform tool">
        <text>Temporary transform tool</text>
        <activationFlags>1</activationFlags>
        <activationConditions>1</activationConditions>
        </Action>

        <Action name="Cycle painting opacity">
        <text>Cycle painting opacity</text>
        <activationFlags>1</activationFlags>
        <activationConditions>1</activationConditions>
        </Action>

        <Action name="Cycle selection tools">
        <text>Cycle selection tools</text>
        <activationFlags>1</activationFlags>
        <activationConditions>1</activationConditions>
        </Action>

        <Action name="Cycle misc tools">
        <text>Cycle misc tools</text>
        <activationFlags>1</activationFlags>
        <activationConditions>1</activationConditions>
        </Action>

        <Action name="Cycle painting blending modes">
        <text>Cycle painting blending modes</text>
        <activationFlags>1</activationFlags>
        <activationConditions>1</activationConditions>
        </Action>

    </Actions>
</ActionCollection>
